import type { MiniApp } from '@xiabao/state';

export const BUILTIN_MINI_APPS: MiniApp[] = [
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    url: 'https://chatgpt.com',
    icon: '/miniapps/chatgpt.svg',
    color: 'bg-[#10A37F] text-white',
    desc: 'OpenAI 官方智能对话助手，多模态与 GPT-4o 强力驱动',
  },
  {
    id: 'claude',
    name: 'Claude',
    url: 'https://claude.ai',
    icon: '/miniapps/claude.svg',
    color: 'bg-[#D97757] text-white',
    desc: 'Anthropic 旗舰大模型，以长文本理解、高级推理和卓越代码著称',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    url: 'https://chat.deepseek.com',
    icon: '/miniapps/deepseek.svg',
    color: 'bg-[#4D6BFE] text-white',
    desc: '深度求索，中文极佳、代码与数学推理极其出色的国产神机',
  },
  {
    id: 'gemini',
    name: 'Gemini',
    url: 'https://gemini.google.com',
    icon: '/miniapps/gemini.svg',
    color: 'bg-gradient-to-tr from-[#4A88E3] to-[#B06AB3] text-white',
    desc: 'Google 官方 AI 助手，超长百万 Token 上下文与深度系统集成',
  },
  {
    id: 'kimi',
    name: 'Kimi Chat',
    url: 'https://kimi.moonshot.cn',
    icon: '/miniapps/kimi.svg',
    color: 'bg-[#E0643B] text-white',
    desc: '月之暗面出品，专注于长文档、超大网页与搜索总结的高级对话助手',
  },
  {
    id: 'doubao',
    name: '豆包',
    url: 'https://www.doubao.com',
    icon: '/miniapps/doubao.svg',
    color: 'bg-[#24C2A3] text-white',
    desc: '字节跳动高品质通用对话与语音对话模型，内置多种实用工具',
  },
  {
    id: 'siliconflow',
    name: 'SiliconFlow',
    url: 'https://cloud.siliconflow.cn',
    icon: '/miniapps/siliconflow.svg',
    color: 'bg-[#8B5CF6] text-white',
    desc: '硅基流动，提供超高速度与极高性价比的国产与开源模型中心',
  },
  {
    id: 'poe',
    name: 'Poe',
    url: 'https://poe.com',
    icon: '/miniapps/poe.svg',
    color: 'bg-[#A324F2] text-white',
    desc: 'Quora 旗下大模型聚合平台，支持定制机器人并体验多款前沿大模型',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    url: 'https://perplexity.ai',
    icon: '/miniapps/perplexity.svg',
    color: 'bg-[#132C2A] text-[#1FC4B2]',
    desc: '世界领先的 AI 搜索引擎，快速提供全网综述并附带权威信源',
  },
  {
    id: 'groq',
    name: 'Groq',
    url: 'https://groq.com',
    icon: '/miniapps/groq.svg',
    color: 'bg-black text-white border border-neutral-800',
    desc: '采用 LPU 推理加速引擎，以数百 Token/s 极速响应通用开源模型',
  },
  {
    id: 'coze',
    name: '扣子 (Coze)',
    url: 'https://www.coze.cn',
    icon: '/miniapps/coze.svg',
    color: 'bg-[#5F56FF] text-white',
    desc: '新一代 AI 智能体/Bot 开发平台，零代码快速编排复杂工作流与插件',
  },
  {
    id: 'dify',
    name: 'Dify',
    url: 'https://dify.ai',
    icon: '/miniapps/dify.svg',
    color: 'bg-[#155EEF] text-white',
    desc: '企业级 LLM 应用开发平台，提供可视化的 Agent 与 RAG 构建工作台',
  },
  {
    id: 'v0',
    name: 'v0.dev',
    url: 'https://v0.dev',
    icon: '/miniapps/v0.svg',
    color: 'bg-[#09090B] text-white border border-neutral-800',
    desc: 'Vercel 出品的前端 AI 生成器，输入文字即可秒级生成美观网页 UI',
  },
  {
    id: 'bolt',
    name: 'Bolt.new',
    url: 'https://bolt.new',
    icon: '/miniapps/bolt.svg',
    color: 'bg-[#0070F3] text-white',
    desc: 'StackBlitz 全栈浏览器级 IDE，使用 AI 直接创建、运行并部署全栈项目',
  },
  {
    id: 'huggingchat',
    name: 'HuggingChat',
    url: 'https://huggingface.co/chat',
    icon: '/miniapps/huggingchat.svg',
    color: 'bg-[#FBBF24] text-[#111827]',
    desc: 'Hugging Face 官方开源模型乐园，抢先体验最新开源 LLM 社区成果',
  },
  {
    id: 'qwen',
    name: '通义千问',
    url: 'https://chat.qwen.lm',
    icon: '/miniapps/qwen.svg',
    color: 'bg-[#673AB7] text-white',
    desc: '阿里巴巴通义旗舰对话助手，中英文理解、逻辑编写与代码功能卓越',
  },
];
